### ISSUE TITLE
tls13.crypto.mozilla.org vs facebook.com for TLS v1.3

### ISSUE THREAD

**Issue by protik77** [nabla-c0d3/sslyze#345] opened 2018-10-22 00:23 UTC
In my Firefox beta v63, both tls13.crypto.mozilla.org and facebook.com is shown as TLS v1.3 supported site. But when I use `sslyze` to get the information, facebook is not recognized as v1.3. Do you guys know why? 

The output json file is attached.
[v13.json.txt](https://github.com/nabla-c0d3/sslyze/files/2499788/v13.json.txt)

**Comment by nabla-c0d3** [comment] 2018-10-28 18:11
Duplicate of #347

**Closed by nabla-c0d3** 2018-10-28 18:11 UTC
