### ISSUE TITLE
sslv3 alert unexpected message when running elliptic_curves

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#496] opened 2021-02-12 15:04 UTC
**Describe the bug**

```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/elliptic_curves_plugin.py", line 118, in result_for_completed_scan_jobs
    all_ecdh_results = [scan_job.result() for scan_job in completed_scan_jobs]
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/elliptic_curves_plugin.py", line 118, in <listcomp>
    all_ecdh_results = [scan_job.result() for scan_job in completed_scan_jobs]
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/elliptic_curves_plugin.py", line 162, in _test_curve
    ssl_connection.connect()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/connection_helpers/tls_connection.py", line 293, in connect
    self.ssl_client.do_handshake()
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/nassl/ssl_client.py", line 182, in do_handshake
    self._ssl.do_handshake()
nassl._nassl.OpenSSLError: error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message
```

**To Reproduce**
Install SSLyze using: pip
Run the following command: /opt/rh/rh-python38/root/usr/bin/python3.8 -m sslyze --regular

**Expected behavior**
Successful scan

**Python environment (please complete the following information):**
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Python version: 3.8
SSLyzeL: 4.0.2

**Comment by nabla-c0d3** [comment] 2021-02-13 03:54
Duplicate of https://github.com/nabla-c0d3/sslyze/issues/490

**Closed as completed by nabla-c0d3** 2021-02-13 03:54 UTC
