### ISSUE TITLE
Broken import on python 3.8

### ISSUE THREAD

**Issue by weddige** [nabla-c0d3/sslyze#426] opened 2020-03-31 14:25 UTC
The import of `typing_extensions` with python 3.8 fails, as it is only a dependency für python 3.7:

https://github.com/nabla-c0d3/sslyze/blob/c8dbf366efc8f7e8e0c4d8939d0c6acd9f557f1f/setup.py#L95

https://github.com/nabla-c0d3/sslyze/blob/4923e8c6d12a7a61c37a681d0253f864fb08e2a8/sslyze/plugins/scan_commands.py#L3

**Comment by nabla-c0d3** [comment] 2020-04-03 03:28
Duplicate of #421

**Closed by nabla-c0d3** 2020-04-03 03:28 UTC
