### ISSUE TITLE
Timeout for all checks on a working host

### ISSUE THREAD

**Issue by cjeanneret** [nabla-c0d3/sslyze#52] opened 2015-02-16 12:04 UTC
Hello,

This is apparently unrelated with #48 as it doesn't affect only SSLv2.

Here's a sample output:
```
 SCAN RESULTS FOR aaa.bbb:443 - yyy.yyy.yyy.yyy:443
 ---------------------------------------------------------------

  * Deflate Compression:
      OK - Compression disabled          

  * Session Renegotiation:
      Client-initiated Renegotiations:   OK - Rejected
      Secure Renegotiation:              OK - Supported

Unhandled exception when processing --certinfo: 
socket.timeout - timed out
                 DES-CBC-SHA                         timeout - timed out                
                 AECDH-NULL-SHA                      timeout - timed out                
                 ADH-DES-CBC-SHA                     timeout - timed out                
                 EDH-RSA-DES-CBC3-SHA                TypeError - cannot concatenate 'str' and 'NoneType' objects
                 ECDHE-RSA-DES-CBC3-SHA              TypeError - cannot concatenate 'str' and 'NoneType' objects
                 ECDHE-RSA-AES256-SHA384             TypeError - cannot concatenate 'str' and 'NoneType' objects
                 ECDHE-RSA-AES256-SHA                TypeError - cannot concatenate 'str' and 'NoneType' objects
[…]
```
It goes on for the other protocols.

Problem: the host is up n'running, working perfectly in a standard browser.

Lemme know of some way to provide the host so that you can test it on your own (host is public, but as I'm not the manager/owner…)

Cheers,

C.

**Comment by nabla-c0d3** [comment] 2015-02-16 16:39
Interesting - can you email me the host ? Email is on my github profile.
Thanks!

**Comment by nabla-c0d3** [comment] 2015-04-04 22:34
Closing this as I can't reproduce it

**Closed by nabla-c0d3** 2015-04-04 22:34 UTC
