### ISSUE TITLE
TypeError in cert info plugin when processing malformed issuer field

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#167] opened 2016-08-18 17:03 UTC
Running the certificate info plugin on `fttesttwai.gov` (port 443) gives the following `TypeError` in `sslyze`:

```
File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 305, in as_text
    text_output.extend(self._get_certificate_text())
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 510, in _get_certificate_text
    issuer_name = unicode(cert_dict['issuer'], 'utf-8')
TypeError: coercing to Unicode: need string or buffer, dict found
```

**Comment by nabla-c0d3** [comment] 2016-08-18 18:54
Duplicate of #160 - will be fixed in the next release.

**Closed** 2016-09-01 04:37 UTC
