### ISSUE TITLE
tls13.crypto.mozilla.org vs facebook.com for TLS v1.3

### ISSUE THREAD

**Issue by protik77** [nabla-c0d3/sslyze#346] opened 2018-10-22 00:30 UTC
When I browse tls13.crypto.mozilla.org or facebook.com using firefox beta v63, both are identified as TLS v1.3 supported site. But `sslyze` identifies the highest SSL version for facebook as TLS v1.2. Do you guys know why?

Please see the attached for output of, `python -m sslyze --regular facebook.com tls13.crypto.mozilla.org --json_out=tst2.json`
[v13.json.txt](https://github.com/nabla-c0d3/sslyze/files/2499794/v13.json.txt)

**Comment by nabla-c0d3** [comment] 2018-10-28 18:11
Duplicate of #347

**Closed by nabla-c0d3** 2018-10-28 18:11 UTC
