### ISSUE TITLE
SSLyze crashes when trying to handle an exception relating to client certificates being needed

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#294] opened 2018-02-27 03:49 UTC
I got a crash in SSLyze when executing a TLS 1.2 scan on a host which requires a client certificate:

```
In [1]: import sslyze

In [2]: sslyze.__version__
Out[2]: '1.3.4'

In [4]: from sslyze.synchronous_scanner import SynchronousScanner
   ...: from sslyze.concurrent_scanner import ConcurrentScanner, PluginRaisedExc
   ...: eptionScanResult
   ...: from sslyze.plugins.openssl_cipher_suites_plugin import Tlsv10ScanComman
   ...: d, Tlsv11ScanCommand, Tlsv12ScanCommand, Sslv20ScanCommand, Sslv30ScanCo
   ...: mmand
   ...: from sslyze.plugins.certificate_info_plugin import CertificateInfoScanCo
   ...: mmand
   ...: from sslyze.ssl_settings import TlsWrappedProtocolEnum
   ...: 

In [5]: server_info = sslyze.server_connectivity.ServerConnectivityInfo(hostname
   ...: ="sdv.max.gov", port=443)

In [6]: server_info.test_connectivity_to_server(network_timeout=30)

In [7]: scanner = SynchronousScanner(network_timeout=30)

In [8]: scanner.run_scan_command(server_info, Tlsv12ScanCommand())
```

```
---------------------------------------------------------------------------
WantX509LookupError                       Traceback (most recent call last)
~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/nassl/ssl_client.py in do_handshake(self)
    162             try:
--> 163                 self._ssl.do_handshake()
    164                 self._is_handshake_completed = True

WantX509LookupError: 

During handling of the above exception, another exception occurred:

ClientCertificateRequested                Traceback (most recent call last)
~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in _test_cipher_suite(server_connectivity_info, ssl_version, openssl_cipher_name)
    235             # Perform the SSL handshake
--> 236             ssl_connection.connect()
    237             cipher_result = AcceptedCipherSuite.from_ongoing_ssl_connection(ssl_connection, ssl_version)

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/utils/ssl_connection.py in connect(self, network_timeout, network_max_retries)
    221                     # SSL handshake
--> 222                     self.ssl_client.do_handshake()
    223 

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/nassl/ssl_client.py in do_handshake(self)
    181                 # Server asked for a client certificate and we didn't provide one
--> 182                 raise ClientCertificateRequested(self.get_client_CA_list())
    183 

ClientCertificateRequested: Server requested a client certificate issued by one of the following CAs: /DC=gov/DC=max/DC=sdv/CN=MAX SDV Client CA.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-671279f6c075> in <module>()
----> 1 scanner.run_scan_command(server_info, Tlsv12ScanCommand())

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/synchronous_scanner.py in run_scan_command(self, server_info, scan_command)
     50         plugin_class = self._plugins_repository.get_plugin_class_for_command(scan_command)
     51         plugin = plugin_class()
---> 52         return plugin.process_task(server_info, scan_command)

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in process_task(self, server_connectivity_info, scan_command)
    202         for failed_job in thread_pool.get_error():
    203             (_, exception) = failed_job
--> 204             raise exception
    205 
    206         thread_pool.join()

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/utils/thread_pool.py in _work_function(job_q, result_q, error_q)
    113         args = job[1]
    114         try:
--> 115             result = function(*args)
    116         except Exception as e:
    117             error_q.put((job, e))

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in _test_cipher_suite(server_connectivity_info, ssl_version, openssl_cipher_name)
    241 
    242         except ClientCertificateRequested:
--> 243             cipher_result = AcceptedCipherSuite.from_ongoing_ssl_connection(ssl_connection, ssl_version)
    244 
    245         except Exception as e:

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in from_ongoing_ssl_connection(cls, ssl_connection, ssl_version)
    372 
    373         status_msg = ssl_connection.post_handshake_check()
--> 374         return AcceptedCipherSuite(picked_cipher_name, ssl_version, keysize, dh_infos, status_msg)
    375 
    376 

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in __init__(self, openssl_name, ssl_version, key_size, dh_info, post_handshake_response)
    349     def __init__(self, openssl_name, ssl_version, key_size, dh_info=None, post_handshake_response=None):
    350         # type: (Text, OpenSslVersionEnum, int, Optional[Dict], Optional[Text]) -> None
--> 351         super(AcceptedCipherSuite, self).__init__(openssl_name, ssl_version)
    352         self.key_size = key_size
    353         self.dh_info = dh_info

~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sslyze/plugins/openssl_cipher_suites_plugin.py in __init__(self, openssl_name, ssl_version)
    321         self.openssl_name = openssl_name
    322         self.ssl_version = ssl_version
--> 323         self.is_anonymous = True if 'anon' in self.name else False
    324 
    325     @property

TypeError: argument of type 'NoneType' is not iterable
```

**Comment by nabla-c0d3** [comment] 2018-02-27 04:04
This might be a duplicate of #289 . Client authentication was broken but it's almost fixed now. Can you try with master? If not it should work fine in the next release (I already added unit tests specifically for the code that crashes here).

**Closed** 2018-03-04 23:48 UTC
Labels: duplicate

**Comment by konklone** [comment] 2018-03-05 01:09
I haven't tested yet, but completely agree it's presumed fixed unless I see it crop up again in future. Thanks!

**Comment by nabla-c0d3** [comment] 2018-03-05 05:32
I closed this as a duplicate, but the issue will be fixed soon.

**Comment by refayathaque** [comment] 2018-10-02 18:12
@konklone did you find this fixed in the latest version of sslyze? If I use the newest version of the dockerized pshtt Lambda will it work?

**Comment by refayathaque** [comment] 2018-10-02 19:10
> @konklone did you find this fixed in the latest version of sslyze? If I use the newest version of the dockerized pshtt Lambda will it work?

It does! :)
