### ISSUE TITLE
sslyze 6.0.0 broken on Fedora 41 (x86-64)

### ISSUE THREAD

**Issue by jduprat** [nabla-c0d3/sslyze#679] opened 2024-12-11 21:46 UTC
**Describe the bug**
Crash when trying to run sslyze

**To Reproduce**
$ python -m venv ~/lib/venv/sslyze
$ source lib/venv/sslyze/bin/activate
$ pip install --upgrade pip setuptools wheel
$ pip install --upgrade sslyze
The install is successful.
$ python --version
Python 3.13.0
$ python -m sslyze
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jld/lib/venv/sslyze/lib64/python3.13/site-packages/sslyze/__main__.py", line 14, in <module>
    from sslyze.cli.output_hub import OutputHub
  File "/home/jld/lib/venv/sslyze/lib64/python3.13/site-packages/sslyze/cli/output_hub.py", line 8, in <module>
    from sslyze.cli.json_output import JsonOutputGenerator
  File "/home/jld/lib/venv/sslyze/lib64/python3.13/site-packages/sslyze/cli/json_output.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl import x509
ImportError: cannot import name 'x509' from 'cryptography.hazmat.backends.openssl' (/home/jld/lib/venv/sslyze/lib64/python3.13/site-packages/cryptography/hazmat/backends/openssl/__init__.py)
$ openssl version
OpenSSL 3.2.2 4 Jun 2024 (Library: OpenSSL 3.2.2 4 Jun 2024)

There is a cryptography rpm package that is installed with the system —
$ rpm -qi python3-cryptography-43.0.0-2.fc41.x86_64
Name        : python3-cryptography
Version     : 43.0.0
Release     : 2.fc41
Architecture: x86_64
Install Date: Thu 21 Nov 2024 01:43:53 PM PST
Group       : Unspecified
Size        : 4926355
License     : (Apache-2.0 OR BSD-3-Clause) AND PSF-2.0
Signature   : RSA/SHA256, Tue 30 Jul 2024 08:33:51 AM PDT, Key ID d0622462e99d6ad1
Source RPM  : python-cryptography-43.0.0-2.fc41.src.rpm
Build Date  : Tue 30 Jul 2024 08:23:04 AM PDT
Build Host  : buildhw-x86-10.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://cryptography.io/en/latest/
Bug URL     : https://bugz.fedoraproject.org/python-cryptography
Summary     : PyCA's cryptography library
Description :
cryptography is a package designed to expose cryptographic primitives and
recipes to Python developers.

However the error above mentions that the package is picked up from /home/jld/lib/venv/sslyze/lib64/python3.13/site-packages/sslyze/cli/ which is what I would expect — it is installed as part of the venv and properly picked up.

**Comment by nabla-c0d3** [comment] 2024-12-21 08:51
SSLyze doesn't support Python 3.13 yet and the version of cryptography that's installed is probably not compatible with Python 3.13 either. Closing this is a duplicate of https://github.com/nabla-c0d3/sslyze/issues/668

**Closed as not planned by nabla-c0d3** 2024-12-21 08:51 UTC
