### ISSUE TITLE
Client side certs fail

### ISSUE THREAD

**Issue by the-room** [nabla-c0d3/sslyze#139] opened 2016-03-10 19:20 UTC
Have been attempting to use it with some client certs (tried v0.13.2 and v0.13.3), which failed with the following error: 

Traceback (most recent call last):
  File "sslyze_cli.py", line 630, in <module>
  File "sslyze_cli.py", line 532, in main
_nassl.OpenSSLError:
error:1418C197:SSL routines:ssl3_shutdown:shutdown while in init

Saw that there were changes in v0.12 e.g.

- A full (client) certificate chain can now be supplied when using client certificates.

So skipped to v0.11 which worked e.g. with the same command line/cert files etc:

.\sslyze.exe --cert="pub.cer" --key="pri.pkcs8" --keyform="PEM" --pass="a" --regular super-secret-host:443

**Comment by janderse** [comment] 2016-03-11 15:21
The bug doesn't happen on Mac OS X.  Ran v0.13.3 on Mac OS X:
./sslyze_cli.py --regular q103.qckr.net

And got the proper output, including this appropriate warning:
WARNING: Server requested optional client authentication

So this may be a nassl bug on Windows?

**Comment by nabla-c0d3** [comment] 2016-03-11 17:29
Thanks for looking into this! I am guessing it is the OpenSSL fork nassl is now using ( #116 ) that does not work well on Windows. I might have to revert to OpenSSL 1.0.1e.

**Comment by janderse** [comment] 2016-03-11 18:16
Sure.  You can scan this public host for debugging:
sslyze_cli.exe --regular q103.qckr.net

**Comment by nabla-c0d3** [comment] 2016-03-12 18:25
Fixed in https://github.com/nabla-c0d3/nassl/commit/0ff01d0b7ff099c613f189804cdd81be7c325d74 and nassl 0.13.4.

**Closed by nabla-c0d3** 2016-03-12 18:25 UTC

**Comment by nabla-c0d3** [comment] 2016-03-12 19:47
@fabian-z Let's move the discussion in #116 here as it relates to this issue. I'm not able to reproduce this on Linux (Debian) 64 bits with the OpenSSL fork. Can you confirm that you are seeing this issue? Which Linux are you using?
Thanks!

**Comment by fabian-z** [comment] 2016-03-12 19:52
@nabla-c0d3 Sure, no problem.
I could reproduce this on an up to date Arch Linux 64bit box. Was trying to use the recommended 1.0.2-chacha fork for my [PKGBUILD](https://aur.archlinux.org/packages/sslyze-git/) instead of the official old OpenSSL 1.0.2e source.
The package works fine as is with the official OpenSSL source, but if trying to use the [OpenSSL fork](https://github.com/PeterMosmans/openssl), the now well-known ```SSL routines:ssl3_shutdown:shutdown while in init``` appears for every scan attempt (also without client certificates).

**Comment by janderse** [comment] 2016-03-12 23:20
This appears to be fixed for Windows by SSLyze v0.13.5.  It is working for me...  This works:
sslyze_cli.exe --regular q103.qckr.net

@fabian-z are you able to scan q103.qckr.net using the latest release?

**Comment by fabian-z** [comment] 2016-03-13 21:35
@janderse The new release reverts to using the official version of OpenSSL instead of the problematic fork, which is why it works for you again. See the reasons for the inital switch to the fork here: #116. This was fixed in binary release for Win32/64, but the issue apparently exists at least for Linux, too, and just reverting to the old version is no long term option because of the reasons outlined in #116.

So the differences between OpenSSL 1.0.2f and the 1.0.2-chacha branch of @PeterMosmans fork have to be bisected to find the offending change and hopefully fix the underlying issue.

As the bug at hand does not exhibit any relation to specific servers for me, your offer of a test endpoint is generous, but imho not needed at the moment. Thank you anyway!

**Comment by fabian-z** [comment] 2016-03-13 21:56
@PeterMosmans  I just tried rebuilding with https://github.com/openssl/openssl/commit/e76f48539109829819aabc03953cf2cfd4612961, which seems to be the latest commit to the OpenSSL_1_0_2-stable branch. 

Unfortunately, the build succeeded, but the test suite failed with
```
======================================================================
ERROR: test_set_cipher_list (SSL_Tests.SSL_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/sslyze-git/src/nassl/tests/SSL_Tests.py", line 107, in test_set_cipher_list
    self.assertIsNone(test_ssl.set_cipher_list("LOW"))
OpenSSLError: 
error:140C5042:SSL routines:ssl_undefined_function:called a function you should not call
error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match
```

However, when ignoring the tests, the scan in fact fails with
```error:140E0197:SSL routines:SSL_shutdown:shutdown while in init```. So the main difference between https://github.com/openssl/openssl/commit/e76f48539109829819aabc03953cf2cfd4612961 and HEAD of 1.0.2-chacha is not erroring out on a scan attempt (as both versions do that identically), but that as of the latest commit for 1.0.2, the official versions fails the test suite, too.

**Comment by nabla-c0d3** [comment] 2016-03-13 22:11
This error with the latest 1.0.2 is most likely because they've removed the LOW cipher suites and SSLv2 starting with 1.0.2f or g. These can only be re-enabled with special compilation directives (and I don't think SSLv2 can be re-enabled ever), hence the "no cipher match" error. 
But it seems like you are getting the "routines:SSL_shutdown:shutdown while in init" error too so this might be due to a change that was introduced in 1.0.2f or g?

**Comment by fabian-z** [comment] 2016-03-13 22:17
That seems logical. The change must have happened between 1.0.2f (which should correspond to https://github.com/openssl/openssl/commit/95605f3ae1ec8857e8cb612ce35805a3b0207d21) and https://github.com/openssl/openssl/commit/e76f48539109829819aabc03953cf2cfd4612961. As I wrote in #116, 1.0.2f passes the test suite and has no errors during scan for me.

**Comment by nabla-c0d3** [comment] 2016-03-13 22:20
Thanks for checking - I will look into this when I have time.

**Comment by fabian-z** [comment] 2016-03-13 22:28
Sure, you're welcome. Maybe it will help you to know that I tried 1.0.2g (https://github.com/openssl/openssl/commit/902f3f50d051dfd6ebf009d352aaf581195caabf) and both the test suite and regular scan attempts fail with multiple ```ImportError: _nassl.so: undefined symbol: SSLv2_method``` errors.

**Comment by nabla-c0d3** [comment] 2016-03-13 22:29
Yes, I tried that too yesterday :). SSLv2 was removed for security reasons.

**Comment by fabian-z** [comment] 2016-03-13 22:34
The baffling part is that I can run a scan attempt when building against the current HEAD of OpenSSL_1_0_2-stable, even though the attempt will error out with ```error:140E0197:SSL routines:SSL_shutdown:shutdown while in init```. When building against OpenSSL_1_0_2g, I get the ```ImportError: _nassl.so: undefined symbol: SSLv2_method```.
Did they somehow re-add the SSLv2 functions?

**Comment by nabla-c0d3** [comment] 2016-03-14 09:51
Here it is: https://github.com/openssl/openssl/issues/710

**Comment by PeterMosmans** [comment] 2016-03-14 10:15
Thanks for researching this @nabla-c0d3 - this means that for this issue the 1.0.2-chacha fork performs 'the same' as the official fork :wink: - as expected :wink:
I'm removing this issue for the 1.0.2-chacha branch.

**Comment by nabla-c0d3** [comment] 2016-03-14 10:19
Yes - sorry about that!
