### ISSUE TITLE
Feature Request: Letter Grades

### ISSUE THREAD

**Issue by chppppp** [nabla-c0d3/sslyze#317] opened 2018-05-24 20:30 UTC
Would be nice if there was some default letter grading for this app similar to ssllabs. 

Thanks! Love the project!

**Comment by happylie** [comment] 2020-01-29 01:53
You are using the project well.

Have you added any features yet?
When is it possible?

**Comment by nabla-c0d3** [comment] 2020-12-13 17:53
Closing this as a duplicate of #441

**Closed by nabla-c0d3** 2020-12-13 17:53 UTC
