### ISSUE TITLE
Crash when server triggers unexpected connection errors due to bad connectivity

### ISSUE THREAD

**Issue by dhaug-op** [nabla-c0d3/sslyze#430] opened 2020-04-20 12:18 UTC
**Describe the bug**
**Please be aware, that this issue affects multiple plugins. I restrict myself to ``tlsv1_2`` here for clarity.**
I often encounter servers just closing the connection on unsupported ciphers. A random example found in the internet is ``asml.com``.

When scanning these Servers with SSLyze 2.x one gets a whole lot of errored ciphers but the output is usable as the accepted ciphers are listed correctly:

```
$ sslyze --version
2.1.4
$ sslyze --tlsv1_2 asml.com
[snip]
 * TLSV1_2 Cipher Suites:
       Forward Secrecy                    OK - Supported
       RC4                                OK - Not Supported

     Preferred:
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384                            256 bits                                       
     Accepted:
        TLS_RSA_WITH_AES_256_GCM_SHA384                                  256 bits
[snip]
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_SEED_CBC_SHA                         ConnectionResetError - [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
        TLS_RSA_WITH_RC4_128_SHA                          ConnectionResetError - [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
        TLS_RSA_WITH_RC4_128_MD5                          ConnectionResetError - [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
[snip]
```

When using SSLyze 3.x on the other hand, even the connectivity check fails:

```
$ sslyze --version
3.0.2
$ sslyze --tlsv1_2 asml.com

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "c:\python-envs\test-opcl\lib\site-packages\nassl\ssl_client.py", line 180, in do_handshake
    self._ssl.do_handshake()
nassl._nassl.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python-envs\test-opcl\Scripts\sslyze-script.py", line 11, in <module>
    load_entry_point('sslyze==3.0.2', 'console_scripts', 'sslyze')()
  File "c:\python-envs\test-opcl\lib\site-packages\sslyze\__main__.py", line 58, in main
    server_connectivity_info = completed_future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python-envs\test-opcl\lib\site-packages\sslyze\server_connectivity.py", line 170, in perform
    ssl_connection.connect(should_retry_connection=False)
  File "c:\python-envs\test-opcl\lib\site-packages\sslyze\connection_helpers\tls_connection.py", line 282, in connect
    self.ssl_client.do_handshake()
  File "c:\python-envs\test-opcl\lib\site-packages\nassl\ssl_client.py", line 191, in do_handshake
    handshake_data_in = self._sock.recv(self._DEFAULT_BUFFER_SIZE)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
```

Thus the host can not be scanned at all with SSLyze 3.0.2.

**To Reproduce**
1. Install SSLyze using ``pip install sslyze``
1. Run the following command `sslyze --tlsv1_2 asml.com`
1. See error

**Expected behavior**
* At best: handle servers closing the connection instead of rejecting the handshake in a concise manner.
* At least: handle this issue in a way allowing to scan such servers, even when one gets lots of ciphers with error.

**Python environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.2

**Additional context**
I already investigated the issue in part. Let me summarize my knowledge:
* in SSLyze 2.x https://github.com/nabla-c0d3/sslyze/blob/2.1.4/sslyze/server_connectivity_tester.py#L279 handled the issue in Connectivity-Test. Such general ``except`` is missing in SSLyze 3.x (see https://github.com/nabla-c0d3/sslyze/blob/3.0.2/sslyze/server_connectivity.py#L207)
* Applying the following diff enables SSLyze 3.x to connect in the first place. Nevertheless, multiple plugins keep to error out.

    ```diff
    diff --git a/sslyze/server_connectivity.py b/sslyze/server_connectivity.py
    index 906c989..deacff6 100644
    --- a/sslyze/server_connectivity.py
    +++ b/sslyze/server_connectivity.py
    @@ -204,7 +204,9 @@ def perform(
                     except TlsHandshakeFailed:
                         # This TLS version did not work; keep going
                         pass
    -
    +                except Exception:
    +                    # Could not complete a handshake with this server
    +                    pass
                     finally:
                         ssl_connection.close()
    ```

* I stopped investigation at this point, as I am not sure or aware how to fix the issue in general. If you can point me in the right direction, I would be happy to create a PR.

I'm sorry for the long description and thank you for your awesome work!
BR

**Comment by nabla-c0d3** [comment] 2020-04-26 23:34
Hello and thanks for the report!

I am unable to reproduce this when connecting to asml.com (I can consistently scan it) so I think this is caused by bad connectivity and/or a slow connection between you and this server. 

However, SSLyze shouldn't crash when that's the case, so instead I changed the code so that it will report this server as one that cannot be scanned.

One of the main goals of SSLyze 3.0.0 is to never return partial results (like what you are seeing when you scan asml.com): either full results, or the server can't be scanned. This is because partial results are not very useful (you still won't know which cipher suites are truly supported) and are very easy to misinterpret.

Hence in the next release, the scan will fail because you are unable to consistently reach the server; this is the expected behavior (as opposed to partial results).

**Comment by nabla-c0d3** [comment] 2020-04-27 03:24
Fixed in v3.0.3.

**Closed by nabla-c0d3** 2020-04-27 03:24 UTC
Labels: bug

**Comment by dhaug-op** [comment] 2020-04-27 07:21
Hi nable-c0d3,

thanks for the quick response and reaction. I get your point of not returning partial results and think this is a valid decision.

As you could not reproduce the issue and I am sure it's not just connection issues, I just quickly tested and have the following results:
* On Windows10 the described connection issue occurs (SSLyze 3.0.2 breaking, SSLyze 3.0.3 failing with error)
* On Linux (Ubuntu 18 VM on the very same Windows host, so same connection) the host can be scanned without problem with SSLyze 3.0.2 and 3.0.3.

So I think there is some underlying problem causing this WinError. I will try to get some insight during the week and open a new issue for that.

BR

**Comment by nabla-c0d3** [comment] 2020-04-27 15:10
Sounds good and thanks!

**Comment by dhaug-op** [comment] 2020-04-29 08:32
We digged a little deeper and hopefully found the base problem. See issue #434.
