### ISSUE TITLE
ScanCommand.CERTIFICATE_INFO returns ScanCommandErrorReasonEnum.BUG_IN_SSLYZE

### ISSUE THREAD

**Issue by jbcurtin** [nabla-c0d3/sslyze#443] opened 2020-06-03 17:59 UTC
hello, the software written works wonderfully. Please accept a bug report

Error running the following type of command in the Python API,

```
scan_req = ServerScanRequest(
  server_info = server_info,
  scan_commands = {ScanCommand.CERTIFICATE_INFO}                                                                  
)
```

`server_scan_result` traceback,
```
print(server_scan_result.scan_commands_errors['certificate_info'].exception_trace)
[Errno 20] Not a directory: '~/.local/share/virtualenvs/cert-scanner-LuJSaku9/lib/python3.7/site-packages/sslyze-3.0.6-py3.7.egg/sslyze/plugins/certificate_info/trust_stores/pem_files/apple.yaml'
```

**Comment by nabla-c0d3** [comment] 2020-06-08 01:06
Hello,
I'm not able to reproduce this. How did you install sslyze and which server are you scanning? You can email it to me if you don't want to post it here.

**Comment by nabla-c0d3** [comment] 2020-06-13 17:10
Closing for now; this had to do with installing SSLyze from the master branch directly.

**Closed by nabla-c0d3** 2020-06-13 17:10 UTC
