### ISSUE TITLE
Error when running robot

### ISSUE THREAD

**Issue by hafedh-trimeche** [nabla-c0d3/sslyze#485] opened 2021-02-01 14:58 UTC
* Server: ----
       * Scan command: robot

       Traceback (most recent call last):
         File "D:\a\sslyze\sslyze\sslyze\scanner.py", line 264, in get_results
         File "D:\a\sslyze\sslyze\sslyze\plugins\robot\implementation.py", line 92, in result_for_completed_scan_jobs
         File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\concurrent\futures\_base.py", line 432, in result
         File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\concurrent\futures\_base.py", line 388, in __get_result
         File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\concurrent\futures\thread.py", line 57, in run
         File "D:\a\sslyze\sslyze\sslyze\plugins\robot\_robot_tester.py", line 183, in test_robot
         File "D:\a\sslyze\sslyze\sslyze\plugins\robot\_robot_tester.py", line 214, in _run_oracle_detection
         File "D:\a\sslyze\sslyze\sslyze\plugins\robot\_robot_tester.py", line 306, in _send_robot_payload
         File "D:\a\sslyze\sslyze\sslyze\connection_helpers\tls_connection.py", line 306, in connect
       sslyze.errors.ServerRejectedTlsHandshake

**Comment by nabla-c0d3** [comment] 2021-02-02 03:25
Duplicate of #484

**Closed as completed** 2021-02-02 03:25 UTC
