### ISSUE TITLE
sslyze 1.4.2 installed via homebrew causes "certinfo: TypeError - object of type 'UnrecognizedExtension' has no len()"

### ISSUE THREAD

**Issue by stefanb** [nabla-c0d3/sslyze#322] opened 2018-07-25 05:47 UTC
I noticed that certinfo fails with letsencrypt certificates:
```
$ sslyze --certinfo letsencrypt.org



 AVAILABLE PLUGINS
 -----------------

  SessionRenegotiationPlugin
  SessionResumptionPlugin
  HttpHeadersPlugin
  RobotPlugin
  CompressionPlugin
  CertificateInfoPlugin
  FallbackScsvPlugin
  OpenSslCipherSuitesPlugin
  HeartbleedPlugin
  OpenSslCcsInjectionPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   letsencrypt.org:443                       => 92.123.27.128 




 SCAN RESULTS FOR LETSENCRYPT.ORG:443 - 92.123.27.128
 ----------------------------------------------------

 * Certificate Information:
Unhandled exception while running --certinfo:
TypeError - object of type 'UnrecognizedExtension' has no len()


 SCAN COMPLETED IN 0.50 S
 ------------------------
```

Not sure which extension is breaking the scan.
Other tests from the `--regular` suite work fine.

I have eperienced the same with older and latest sslyze version:
```
$ sslyze --version
1.4.2
```

Same problem can be seen on prominent sites with certificates from various issuers:
* letsencrypt.org (Let's Encrypt) - https://www.ssllabs.com/ssltest/analyze.html?d=letsencrypt.org
* mozilla.org (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=mozilla.org
* wikipedia.org (GlobalSign) - https://www.ssllabs.com/ssltest/analyze.html?d=wikipedia.org
* facebook.com (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=facebook.com
* amazon.com (DigiCert) -https://www.ssllabs.com/ssltest/analyze.html?d=amazon.com
* twitter.com (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=twitter.com
* yahoo.com (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=yahoo.com
* github.com (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=github.com
* wordpress.com (Go Daddy) - https://www.ssllabs.com/ssltest/analyze.html?d=wordpress.com
* reddit.com (DigiCert) 
* jquery.org (Let's Encrypt) 
* videolan.org (Let's Encrypt) 

Works fine testing:
* google.com (Google Internet Authority) - https://www.ssllabs.com/ssltest/analyze.html?d=google.com
* stackoverflow.com (DigiCert) - https://www.ssllabs.com/ssltest/analyze.html?d=stackoverflow.com
* moz.com (CloudFlare) - https://www.ssllabs.com/ssltest/analyze.html?d=moz.com
* slo-tech.com (Comodo) - https://www.ssllabs.com/ssltest/analyze.html?d=slo-tech.com

According to #320, #311 and #293 this seems to be caused by unmet (poorly defined?) dependancy, an outdated version of `cryptography`, likely to be fixed in the homebrew formula:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/sslyze.rb#L46
@nabla-c0d3, could you check the dependancies and resources in that formula, so that we can ask them for a fix?

Last relevant changes were done as part of https://github.com/Homebrew/homebrew-core/pull/28332  :
* https://github.com/Homebrew/homebrew-core/commit/f19782edf2694bbec61fdddd4e0295680f9632e7 (by @ilovezfs and @mistydemeo)
* https://github.com/Homebrew/homebrew-core/commit/52a167e08869396f734567550c0b1a877df05fc4 (by @BrewTestBot and @mistydemeo)

**Comment by regenscheid** [comment] 2018-07-25 15:19
I've been struggling with this, too, on Mac 10.12.  When I installed Sslyze 1.4.2 via homebrew, I get these same errors.  It doesn't seem like its old cryptography or OpenSSL.  As far as I can tell, I'm running cryptography v2.2.2, and OpenSSL 1.0.2o.  But, it's hard to tell what packages are using what versions of OpenSSL that are scattered around everywhere.

Have you tried installing via pip?

I largely gave up on using brew, figuring I had more control over pip.  But I can't get sslyze 1.4.2 to install using pip, as described in #306.  It looks like nassl might not be compatible with Python 3.7, so that might explain why I can't do it from my python3 virtualenv.  But I also can't install it via pip with Python 2.7.15.

**Comment by stefanb** [comment] 2018-07-26 07:43
Generally I have no problems with other homebrew packages. 
Maybe adding some path to `$PATH` here and there...

**Comment by stefanb** [comment] 2018-07-26 08:29
I have opened https://github.com/Homebrew/homebrew-core/issues/30489

**Comment by nabla-c0d3** [comment] 2018-07-26 08:49
It's a duplicate of #320. The cryptography module may or may not support features depending on the OpenSSL version installed on the system (even when using the latest version of cryptography).

As for macOS, only Python 3.6 is supported at the moment. Python 3.7 will be supported in the next release.

**Comment by nabla-c0d3** [comment] 2018-07-26 08:50
The root cause is that SSLyze uses cryptography to parse the Certificate Transparency extension of certificates. Cryptography can only do it if OpenSSL is recent enough on the system.

**Comment by stefanb** [comment] 2018-07-26 09:38
As i understand the solution to #320 was to provide only available data instead of crashing, not really ensuring that the details could be provided.

Is there really no way to define which OpenSSL version should be used and make sure that one is installed?

I have chaos at the moment:
```
$ brew search openssl
==> Formulae
glib-openssl                                                openssl@1.1 ✔
openssl ✔                                                   homebrew/portable-ruby/portable-openssl
$ brew upgrade openssl
Error: openssl 1.0.2o_2 already installed
$ brew upgrade openssl@1.1
Error: openssl@1.1 1.1.0h already installed
$ which openssl
/usr/bin/openssl
$ openssl version
LibreSSL 2.2.7
```
:)

**Comment by regenscheid** [comment] 2018-07-27 13:45
I'm not sure what to make of the behavior I'm seeing.  

First, I'll note that if I install sslyze v1.3.4 via pip, I don't see these certinfo errors. They only happen when I'm on sslyze 1.4.2 (which I can only install via brew).  Under 1.3.4, sslyze correctly identifies the SCTs.

Second, I'm confused about what version of OpenSSL is being used by cryptography. I know Apple includes an old version in Mac OS, but python seems to be using the newer version I installed:
`
(p3env) macmachine:.virtualenvs user$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2o  27 Mar 2018
`
I'm hoping the next release that supports Python 3.7 will work fine when I install it via pip.  But, I don't understand why sslyze v1.3.4 works (when installed via pip), but v1.4.2 doesn't (when installed via brew).

**Comment by nabla-c0d3** [comment] 2018-07-28 22:30
Ultimately this is a bug in cryptography and not SSLyze. The discussion has moved to #323 so I am closing this as a duplicate.

**Closed by nabla-c0d3** 2018-07-28 22:30 UTC

**Comment by stefanb** [comment] 2018-08-14 19:00
This was fixed in scope of https://github.com/Homebrew/homebrew-core/issues/30489 via https://github.com/Homebrew/homebrew-core/pull/30794
