### ISSUE TITLE
cipher suite naming convention

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#58] opened 2015-03-04 00:38 UTC
I noticed that sslyze uses hyphenated names (ex: `ECDHE-ECDSA-NULL-SHA`) but most people identify TLS cipher suites using underscores (ex: `TLS_RSA_EXPORT_WITH_DES40_CBC_SHA`). Should both names be included in the output? Is there a canonical naming convention for cipher suites?

**Comment by postmodern** [comment] 2015-03-04 00:51
Ah, apparently the `FOO-BAR` names are an artifact of OpenSSL. https://www.openssl.org/docs/apps/ciphers.html

**Comment by nabla-c0d3** [comment] 2015-04-04 22:33
Closing this a duplicate of issue #66

**Closed by nabla-c0d3** 2015-04-04 22:33 UTC
