### ISSUE TITLE
Bug: if port is not 443

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/sslyze#213] opened 2017-05-10 10:28 UTC
is it possible that if u scan an address with a port, different that 443, there will be an endless loop which result in a permanent 100% cpu usage?

i have an example address, but this one is very confidential.

can u please confirm my guess, that the port is an issue?

otherwise i can give u the example address via email.

maybe also a reason could be, that sslv2 ciphers do not respond as expected in version 1.0.0.
maybe the exception handling in 1.1.0 is broken?

**Comment by konklone** [comment] 2017-05-15 05:44
If #217 is related, then that would suggest the port is not an issue -- that hangs forever on port 443.

I also tried running the same set of plugins (I expanded the `--regular` scan to the full set of flags it represents) but without the `--sslv2` flag, and it hung just the same.

**Comment by konklone** [comment] 2017-05-15 05:48
I did some more poking, and removing the `--heartbleed` scan was what fixed it and allowed the scan to complete. Give that a shot.

**Comment by nabla-c0d3** [comment] 2017-05-18 06:36
I don't think the port number has any impact on the results (except that the web server might be different), but it looks like this is a duplicate of #217 ? @ericrange can you confirm?

**Comment by ericrange** [comment] 2017-05-18 11:29
at the time i cant reproduce the error because the failure occurs for a website which is down due to wannecry updates^^

but as i already suggested, there is defintly an issue with sslv2, therefore very likly that the heartbleed plugin is responsible for this.

**Comment by ericrange** [comment] 2017-05-18 11:32
but i dont think that the heartbleed check, in particular, causes the stuck. i think there is a broken exception handling that causes an endless loop which is responsible for the 100% cpu usage and therefor for the infinite hang.

**Comment by nabla-c0d3** [comment] 2017-05-20 23:15
@ericrange can you try with the fix I pushed for #217 ?

**Closed** 2017-06-18 22:44 UTC
