### ISSUE TITLE
[Request] Ability to show which ciphers support Forward Secrecy

### ISSUE THREAD

**Issue by RedTechie** [nabla-c0d3/sslyze#121] opened 2016-02-03 14:43 UTC
Consider this a lower priority as really only two cipher groups support FS (https://en.wikipedia.org/wiki/Forward_secrecy), DHE and ECDHE. So one could always put conditions around wrapper logic. But it would be great if the tool showed it natively.

**Comment by nabla-c0d3** [comment] 2016-02-04 20:13
Closing this as a duplicate of #111

**Closed by nabla-c0d3** 2016-02-04 20:13 UTC

**Comment by RedTechie** [comment] 2016-02-04 21:58
This isn't exactly a duplicate of XML outpu request. I mentioned wrapping code as a work around.
